### ISSUE TITLE
itemController.deleteItemにawaitの追加

### ISSUE THREAD

**Issue by 10inoino** [taroosg/nest-todo#2]
只今nest.jsを勉強中の者で、taroosgさんのブログを基にチュートリアルでTODOアプリを作らせてもらいました！
すごく勉強になりました！

ただ、１点気になったところがあったので、issue飛ばさせていただきますm(_ _)m

https://github.com/taroosg/nest-todo/blob/10e4fc26fb1bdca56ec6ee029b6466b1cf61500d/src/item/item.controller.ts#L63
上記の箇所がawaitが無いため、非同期になってしまい、promiseがpendingの状態で64行目のif分岐に入ってしまうため、実際には削除しようとしたレコードがDBになくても、404が出ないという事象が起こりました。
私はここにawaitを入れたら解消されたので、issueを飛ばさせていただきます！

私のコーディングミスの可能性もあるので、お時間あれば精査頂いた上で、修正ご検討いただければと思います。
よろしくお願い致しますm(_ _)m

**Comment by taroosg** [comment]
10inoinoさんこんにちは！

弊ブログをご覧いただきありがとうございます．
多少なりとも参考になったようでとても嬉しく思います！

早速コード確認しまして，確かにawaitがないと正しく動作しませんね．．．当方の検証不足でした．

該当リポジトリの内容修正しましてcommitしました！

https://github.com/taroosg/nest-todo/commit/30941a337d737439ff8ba85ad05f133505b318a0

また，ブログの記載内容も修正しております！
こちらも見落としていた部分で助かりました！ありがとうございました！
